### ISSUE TITLE
51 Errors when building

### ISSUE THREAD

**Issue by GeorgeYDesign** [cometchat-pro-samples/ios-swift-chat-app-swift-4.2#1]
Hey!

I have been trying to build the application but there are 51 errors that are preventing me from building.

The errors are in the following files;
- ChatViewController.swift (7 errors)
- Skype.swift (44 errors)

**Comment by pushpsenairekar2911** [comment]
Hello @GeorgeYDesign, Kindly take the fresh pull of the project and then run it. Also, use a physical device for running the project.  

If you're using Xcode 10.2.1(Swift 5.0) then use this sample app: https://github.com/cometchat-pro-samples/ios-swift-chat-app. You can able to run this one on the simulator.

**Comment by pushpsenairekar2911** [comment]
@GeorgeYDesign  closing this issue since no modifications required. If anything needed then please contact us on  our slack channel: https://cometchat.slack.com/archives/CKXTN3L10
